"""empty message

Revision ID: 04db4adaa8c0
Revises: 
Create Date: 2026-04-04 18:41:22.527405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04db4adaa8c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_info',
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('survey_year', 'item', 'farm_num')
    )
    op.create_table('item_variety',
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('variety_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('variety_id'),
    sa.UniqueConstraint('item', 'variety_name', name='item_variety_uq')
    )
    op.create_table('member',
    sa.Column('mem_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mem_name', sa.String(length=50), nullable=True),
    sa.Column('mem_email', sa.String(length=100), nullable=True),
    sa.Column('mem_password', sa.String(length=200), nullable=True),
    sa.Column('mem_phone', sa.String(length=20), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mem_no'),
    sa.UniqueConstraint('mem_email')
    )
    op.create_table('cultivation_info',
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=True),
    sa.Column('harvest_part', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('greenhouse_type', sa.String(length=50), nullable=True),
    sa.Column('greenhouse_form', sa.String(length=50), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('planting_area', sa.Float(), nullable=True),
    sa.Column('planting_density', sa.Float(), nullable=True),
    sa.Column('planting_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['farm_info.survey_year', 'farm_info.item', 'farm_info.farm_num'], ),
    sa.PrimaryKeyConstraint('survey_year', 'item', 'farm_num')
    )
    op.create_table('environment',
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('measure_time', sa.DateTime(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('harvest_part', sa.Integer(), nullable=True),
    sa.Column('out_temp', sa.Float(), nullable=True),
    sa.Column('out_wind_direction', sa.Integer(), nullable=True),
    sa.Column('out_wind_speed', sa.Float(), nullable=True),
    sa.Column('solar_radiation', sa.Integer(), nullable=True),
    sa.Column('solar_radiation_sum', sa.Integer(), nullable=True),
    sa.Column('rain', sa.Integer(), nullable=True),
    sa.Column('inside_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('carbon_dioxide', sa.Integer(), nullable=True),
    sa.Column('soil_temp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['farm_info.survey_year', 'farm_info.item', 'farm_info.farm_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_year', 'item', 'farm_num', 'measure_time')
    )
    op.create_table('growth_data',
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('measure_time', sa.DateTime(), nullable=False),
    sa.Column('plant_num', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('harvest_part', sa.Integer(), nullable=True),
    sa.Column('branch_num', sa.Integer(), nullable=True),
    sa.Column('plant_height', sa.Float(), nullable=True),
    sa.Column('growth_length', sa.Float(), nullable=True),
    sa.Column('leaf_count', sa.Integer(), nullable=True),
    sa.Column('leaf_length', sa.Float(), nullable=True),
    sa.Column('leaf_width', sa.Float(), nullable=True),
    sa.Column('branch_width', sa.Float(), nullable=True),
    sa.Column('cluster_height', sa.Float(), nullable=True),
    sa.Column('blooming_width', sa.Integer(), nullable=True),
    sa.Column('fruits_width', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['farm_info.survey_year', 'farm_info.item', 'farm_info.farm_num'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_year', 'item', 'farm_num', 'measure_time', 'plant_num')
    )
    op.create_table('production_data',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('production_date', sa.DateTime(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['farm_info.survey_year', 'farm_info.item', 'farm_info.farm_num'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('production_data_daily',
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('shipment_date', sa.DateTime(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['farm_info.survey_year', 'farm_info.item', 'farm_info.farm_num'], ),
    sa.PrimaryKeyConstraint('survey_year', 'item', 'farm_num', 'shipment_date')
    )
    op.create_table('production_data_raw',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('shipment_date', sa.DateTime(), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['farm_info.survey_year', 'farm_info.item', 'farm_info.farm_num'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('cultivation_variety',
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=40), nullable=False),
    sa.Column('farm_num', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['survey_year', 'item', 'farm_num'], ['cultivation_info.survey_year', 'cultivation_info.item', 'cultivation_info.farm_num'], ),
    sa.PrimaryKeyConstraint('survey_year', 'item', 'farm_num', 'variety')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cultivation_variety')
    op.drop_table('production_data_raw')
    op.drop_table('production_data_daily')
    op.drop_table('production_data')
    op.drop_table('growth_data')
    op.drop_table('environment')
    op.drop_table('cultivation_info')
    op.drop_table('member')
    op.drop_table('item_variety')
    op.drop_table('farm_info')
    # ### end Alembic commands ###
